config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'users/index'
  get 'users/new'
  get 'users/create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
  collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oder.rb
class Oder < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    require 'csv'
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            Product.create! row.to_hash
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])
	end

	def new
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path, notice: "The product #{@product.name} has been created."
		else
			render "new"
		end
	end

	private def product_params
		params.require(:product).permit(:name, :image, :description, :price)
	end

	def edit
		@product = Product.find(params[:id])
	end
	
	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
		redirect_to @product
		else
		render 'edit'
		end
	end
	
	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		redirect_to products_path, notice:  "The product #{@product.name} has been deleted."
	end

	def import
		Product.import(params[:file])
		puts params[:file]
		redirect_to products_path, notice: "The data has been imported."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learning</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class = "container" style = "padding-top:20px;">
         <%= yield %>
      </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>New Product</h1>

<%= form_with(model: @product, local: true) do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "form-control" %>
    </p>

    <p>
        <%= form.label :image %><br>
        <%= form.file_field :image, class: "form-control" %>
    </p>
      
    <p>
        <%= form.label :description %><br>
        <%= form.text_field :description, class: "form-control" %>
    </p>

    <p>
        <%= form.label :price %><br>
        <%= form.text_field :price, class: "form-control" %>
    </p>

  <p>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </p>
<% end %>
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing product</h1>

<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
   </div>
<% end %>

<table class="table table-bodered">
    <tr>
        <th>Name</th>
        <th>Image</th>
        <th>Description</th>
        <th>Price</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
 
    <% @products.each do |product| %>
        <tr>
            <td><%= product.name %></td> 
            <td><%= image_tag ("#{product.image}"), size: "200x200"%></td>
            <td><%= product.description %></td>
            <td><%= product.price %></td>
            <td><%= link_to 'Show', product_path(product) %></td>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product_path(product),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
            </td>
        </tr>
    <% end %>
</table>

<div>
<h2>Import data</h2>
    <%= form_tag import_products_path, multipart:true do %>
        <%= file_field_tag :file %>
        </br>
        <%= submit_tag "Import CSV", class: "btn btn-primary"%>
    <% end %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_with scope: :product, url: products_path, local: true do |form| %>
    <p>
        <%= form.label :name %><br>
        <%= form.text_field :name, class: "form-control" %>
    </p>

    <p>
        <%= form.label :image %><br>
        <%= form.text_field :image, class: "form-control" %>
    </p>

    <p>
        <%= form.label :description %><br>
        <%= form.text_field :description, class: "form-control" %>
    </p>

    <p>
        <%= form.label :price %><br>
        <%= form.text_field :price, class: "form-control" %>
    </p>

    <p>
        <%= form.submit "Save", class: "btn btn-primary" %>
    </p>
<% end %>   

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>
 
<p>
  <strong>Image:</strong>
  <%= image_tag ("#{@product.image}"), size: "300x300" %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>